//
//  MockData.swift
//  ShopApp
//
//  Created by Danylo Liubyi on 09.10.2025.
//

import Foundation

enum MockData {
    static let products: [Product] = [
        Product(name: "Nike Air Max 270",
                description: "Comfortable sneakers for everyday wear with Air Max cushioning technology.",
                price: 149.99,
                imageName: "nike_air_max_270"),
        Product(name: "Nike Air Force 1",
                description: "Classic Nike sneakers with timeless design and reliable comfort.",
                price: 129.99,
                imageName: "nike_air_force_1"),
        Product(name: "Nike React Infinity Run",
                description: "Lightweight running shoes with React foam for smooth rides.",
                price: 159.99,
                imageName: "nike_react_infinity"),
        Product(name: "Adidas Ultraboost 22",
                description: "Lightweight and breathable running shoes with Boost midsole for energy return.",
                price: 179.99,
                imageName: "adidas_ultraboost_22"),
        Product(name: "Adidas NMD_R1",
                description: "Trendy sneakers with Primeknit upper and responsive EVA midsole.",
                price: 139.99,
                imageName: "adidas_nmd_r1"),
        Product(name: "Adidas Superstar",
                description: "Iconic shell-toe sneakers with classic street style.",
                price: 99.99,
                imageName: "adidas_superstar"),
        Product(name: "Puma RS-X³",
                description: "Bright and stylish sneakers suitable for sports and casual wear.",
                price: 129.99,
                imageName: "puma_rsx3"),
        Product(name: "Puma Suede Classic",
                description: "Timeless Puma sneakers with suede upper and retro design.",
                price: 89.99,
                imageName: "puma_suede_classic"),
        Product(name: "New Balance 990v5",
                description: "Classic sneakers offering premium comfort and excellent foot support.",
                price: 199.99,
                imageName: "new_balance_990v5"),
        Product(name: "New Balance 327",
                description: "Retro-inspired sneakers with modern comfort technology.",
                price: 119.99,
                imageName: "new_balance_327"),
        Product(name: "Reebok Nano X2",
                description: "Durable training sneakers designed for CrossFit and intense workouts.",
                price: 139.99,
                imageName: "reebok_nano_x2"),
        Product(name: "Reebok Classic Leather",
                description: "Simple yet stylish sneakers with leather upper for casual wear.",
                price: 89.99,
                imageName: "reebok_classic_leather"),
        Product(name: "Asics Gel-Kayano 28",
                description: "Stable running shoes with GEL technology for cushioning and comfort.",
                price: 159.99,
                imageName: "asics_gel_kayano_28"),
        Product(name: "Asics Gel-Nimbus 24",
                description: "Premium cushioned running shoes with GEL and FlyteFoam technologies.",
                price: 179.99,
                imageName: "asics_gel_nimbus_24"),
        Product(name: "Converse Chuck Taylor All Star High",
                description: "Classic high-top sneakers with the legendary Chuck Taylor style.",
                price: 79.99, imageName: "converse_chuck_high"),
        Product(name: "Converse Chuck Taylor All Star Low",
                description: "Low-top version of the iconic Chuck Taylor sneakers.",
                price: 69.99,
                imageName: "converse_chuck_low"),
        Product(name: "Vans Old Skool",
                description: "Iconic low-top sneakers with timeless Vans design.",
                price: 69.99,
                imageName: "vans_old_skool"),
        Product(name: "Vans Sk8-Hi",
                description: "High-top Vans sneakers with classic skate style and comfort.",
                price: 74.99,
                imageName: "vans_sk8_hi"),
        Product(name: "Jordan Air 1 Mid",
                description: "Legendary Air Jordan sneakers with classic design and comfort.",
                price: 159.99,
                imageName: "jordan_air1_mid"),
        Product(name: "Jordan Air 1 Low",
                description: "Low-top Air Jordan sneakers with the same iconic style.",
                price: 149.99,
                imageName: "jordan_air1_low")
    ]
}
